import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

async function render(pathname = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}-${pathname}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request(`http://localhost${pathname}`, { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the engine-backed landing page", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);
  const html = await response.text();
  assert.match(html, /<title>Meander — Every Walk Leaves a Pattern<\/title>/i);
  assert.match(html, /Generated by the Go engine/);
  assert.match(html, /One walk[\s\S]*Four decisions/);
  assert.match(html, /28 private drafts/);
  assert.match(html, /WALK-ART-V1/);
  assert.match(html, /\/generated\/central-park\.svg/);
  assert.match(html, /Actual canonical artwork generated from Central Park/);
  assert.match(html, /What it reads/);
  assert.match(html, /What changes in the art/);
  assert.match(html, /No personal history is required/);
  assert.match(html, /Create from a GPX/);
  assert.match(html, /© OpenStreetMap contributors/);
  assert.doesNotMatch(html, /react-loading-skeleton|Your site is taking shape/);
});

test("server-renders the creation studio and keeps engine assets present", async () => {
  const response = await render("/create");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /LOCAL CREATION STUDIO/);
  assert.match(html, /Generate the artwork/);
  assert.match(html, /restrained broken path/);
  assert.match(html, /One walk · one canonical artwork/);
  assert.doesNotMatch(html, /three finalists|Art system|Color system/);
  assert.match(html, /GPX \/ OSM XML/);

  const [page, engine, api, central, highLine] = await Promise.all([
    readFile(new URL("../app/create/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../backend/internal/engine/engine.go", import.meta.url), "utf8"),
    readFile(new URL("../backend/cmd/api/main.go", import.meta.url), "utf8"),
    access(new URL("../public/generated/central-park.svg", import.meta.url)),
    access(new URL("../public/generated/high-line.svg", import.meta.url)),
  ]);
  assert.match(page, /\/api\/v1\/generate/);
  assert.match(page, /Array\.isArray\(body\.events\)/);
  assert.match(engine, /const Version = "field-3\.2\.0"/);
  assert.match(engine, /func Generate/);
  assert.match(api, /POST \/api\/v1\/generate/);
  assert.equal(central, undefined);
  assert.equal(highLine, undefined);
});
