"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const API = (process.env.NEXT_PUBLIC_MEANDER_API_URL || "http://localhost:8080").replace(/\/$/, "");
type Artwork = { id: string; title: string; subtitle: string; palette: string; preview_url: string; artwork_url: string; visibility: string; features?: { DistanceKM?: number; HardTurns?: number; DurationMinutes?: number }; score?: { Total?: number } };

export default function SharedArtwork({ params }: { params: Promise<{ shareId: string }> }) {
  const [artwork, setArtwork] = useState<Artwork | null>(null); const [error, setError] = useState(false);
  useEffect(() => { params.then(({ shareId }) => fetch(`${API}/api/v1/share/${shareId}`).then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then(setArtwork).catch(() => setError(true))); }, [params]);
  if (error) return <main className="share-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-line" />Meander</Link></header><div className="share-state"><h1>This work is private.</h1><Link className="primary-action" href="/">Explore Meander <span>↗</span></Link></div></main>;
  if (!artwork) return <main className="share-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-line" />Meander</Link></header><div className="share-state">Loading a walk’s pattern…</div></main>;
  const distance = artwork.features?.DistanceKM?.toFixed(2) || "—";
  return <main className="share-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-line" />Meander</Link><Link className="nav-cta" href="/create">Make your own <span>↗</span></Link></header><section className="share-work"><div className="share-art"><img src={`${API}${artwork.preview_url}`} alt={`Meander artwork for ${artwork.title}`} /></div><div className="share-copy"><p className="section-kicker">A walk, interpreted</p><h1>{artwork.title}</h1><p>{artwork.subtitle}</p><div className="share-metrics"><div><span>Distance</span><strong>{distance} km</strong></div><div><span>Turns</span><strong>{artwork.features?.HardTurns ?? "—"}</strong></div><div><span>Quality</span><strong>{artwork.score?.Total?.toFixed(3) ?? "—"}</strong></div></div><a className="primary-action" href={`${API}${artwork.artwork_url}`} download>Download SVG <span>↓</span></a><p className="share-note">Generated by Meander’s route-turbulence engine. The movement is preserved as direction, texture, color, and a quiet trace of the original path.</p></div></section></main>;
}
